#!/usr/bin/env bash

# Generate Ansible inventory from Terraform output
# Usage: ./generate_inventory.sh > inventory.ini

set -euo pipefail

# Default private key path
DEFAULT_SSH_KEY="~/.ssh/id_ed25519"
ANSIBLE_SSH_KEY="${ANSIBLE_SSH_KEY:-$DEFAULT_SSH_KEY}"

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "ERROR: jq is required but not installed." >&2
    exit 1
fi

# Get terraform output as JSON
tf_json=$(terraform output --json 2>/dev/null || true)
if [[ -z "$tf_json" ]]; then
    echo "ERROR: 'terraform output --json' returned nothing. Are you in a Terraform directory?" >&2
    exit 1
fi

# Extract vm_metadata value
vm_metadata=$(echo "$tf_json" | jq -c '.vm_metadata.value // {}')
if [[ "$vm_metadata" == "{}" ]]; then
    echo "ERROR: No vm_metadata found in terraform output." >&2
    exit 1
fi

# Get list of keys (VM names)
keys=$(echo "$vm_metadata" | jq -r 'keys[]')

# Initialize output strings
controllers=""
workers=""

for key in $keys; do
    hostname=$(echo "$vm_metadata" | jq -r --arg k "$key" '.[$k].hostname')
    ip=$(echo "$vm_metadata" | jq -r --arg k "$key" '.[$k].ip_addresses[0].ip_address // empty')
    user=$(echo "$vm_metadata" | jq -r --arg k "$key" '.[$k].username // "user"')
    
    if [[ -z "$hostname" || -z "$ip" ]]; then
        echo "WARNING: Missing hostname or IP for $key, skipping" >&2
        continue
    fi

    if [[ "$key" == k8s-controller-* ]]; then
        controllers+="$hostname ansible_host=$ip ansible_user=$user"$'\n'
    elif [[ "$key" == k8s-worker-* ]]; then
        workers+="$hostname ansible_host=$ip ansible_user=$user"$'\n'
    else
        echo "WARNING: Unknown key pattern '$key', ignoring" >&2
    fi
done

# Generate inventory.ini with configurable SSH key
cat << EOF
##################################################
## Auto generated by $(basename "$0") script    
##################################################
[controllers]
$controllers
[workers]
$workers
[k8s_cluster:children]
controllers
workers

[all:vars]
ansible_ssh_private_key_file=$ANSIBLE_SSH_KEY
ansible_ssh_common_args='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
EOF

