#cloud-config for bridge network
hostname: ${hostname}
fqdn: ${hostname}.${domain}
manage_etc_hosts: true

users:
  - name: ${username}
    ssh_authorized_keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    shell: /bin/bash
%{ if debug_enabled ~}
    lock_passwd: false # allow password login
# openssl passwd -6 -salt $(openssl rand -base64 12) <text-plain-passwd>
    hashed_passwd: "$6$/37IEzBDANE2zJEP$q9yES.ANONpvHrr.tbBdmrLvhZluaxIfgX2acTnvuJIMHgka2Num9L1lufk6xHr.aYMcP.RTtv8HluNlyEdcH1"
%{ endif ~}

# Format and mount data disk
fs_setup:
  - label: data_disk
    filesystem: ext4
    device: detect-zero  # Finds first unformatted disk
    partition: auto

mounts:
  - [ "LABEL=data_disk", "/mnt/data", auto, "defaults,nofail", "0", "0" ]

timezone: ${timezone}
package_update: true

packages:
%{ for package in packages ~}
  - ${package}
%{ endfor ~}

runcmd:
  - systemctl enable --now qemu-guest-agent